In [19]:
import os, numpy as np, nibabel as nib, SimpleITK as sitk, json, csv, cv2, re, random
from tqdm import tqdm, trange
from tqdm.contrib import tzip
from os.path import join, basename, exists, splitext
from shutil import copy, copytree
from glob import glob, iglob
from sklearn.model_selection import train_test_split

In [26]:
data1 = nib.load('1.nii.gz')
data2 = nib.load('2.nii.gz')

In [28]:
arr = data1.get_fdata()

In [30]:
np.unique(arr)

array([0, 1, 2, 4], dtype=uint8)

In [32]:
newdata = np.where(arr==2, 0, arr)

In [33]:
np.unique(newdata)

array([0, 1, 4], dtype=uint8)

In [43]:
foo = np.array([0,1,2,3,4])
np.where(foo == 3, -1, foo)

array([ 0,  1,  2, -1,  4])